services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      SERVICES: secretsmanager
      DEBUG: 1
      DEFAULT_REGION: us-east-2
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17-alpine
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: aryon
      POSTGRES_PASSWORD: aryon
      POSTGRES_DB: aryondb
    volumes:
      - postgres_data:/data/postgres
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "aryon"]
      interval: 10s
      timeout: 5s
      retries: 5
  connector-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: aryon
      DB_PASSWORD: aryon
      DB_NAME: aryondb
      AWS_REGION: us-east-2
      AWS_ENDPOINT: http://localstack:4566
      GRPC_PORT: 50051
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50051"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  localstack_data:
  postgres_data:

networks:
  default:
    name: aryon_network
